version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    tty: true
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: coupleapp-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: matusita394
      MYSQL_DATABASE: coupleapp

